server:
  port: 7001

spring:
  application:
    name: consumer
  datasource:
    url: ${JDBC_DATASOURCE_URL} # jdbc:postgresql://localhost:5432/rabbitMQPracticeDB
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'root'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false
    host: ${SPRING_RABBITMQ_HOST} # localhost
    port: 5672

resolute:
  rabbitmq:
    publishQueueName: resolute-run-request
    exchange: resolute

rabbitmq:
  exchanges:
    topic-exchange: internal.topic.exchange
  queues:
    queue: consumer.queue
  routing-keys:
    key: consumer.routing-key
